# Site settings
title: James Owen | Freelancer
intro: Hello! I'm James Owen.
email: jamie.edwards0122@gmail.com
url: https://jimbojoho.github.io
description: "Multifaceted digital designer."
keywords: "your keywords, separated by commas"
meta_author: James Owen

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
contact: static

# Color settings 
color:
  primary: EDF2F4 
  secondary: 2B2D42  
  secondary-dark: 5565F1 

# Footer settings
footer:
  copyright: James Owen
  # location: Location
  # social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 
    url: 
 

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line:

# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
